### ISSUE TITLE
How to make it so that we can handle admin and user privileges seperately. 

### ISSUE THREAD

**Issue by Mohit-sankhla02** [hkirat/full-stack-assignment#98]
I had a doubt, do we need to create a different admin array just like users that stores the admins of the website. I was asking this because what if I wanted to add a question to the questions array. A normal user shouldn't be allowed to do that. 

And how will the function verify if I am an admin or a user.

**Comment by abhishek-AKT** [comment]
I think by using random tokens we can differentiate between user and admin or we can make a separate route for admin data

**Comment by abishek-william** [comment]
There may be many other ways but a simple solution comes in my mind is, we can use a boolean value to determine whether the person who triyng to add question is a admin or not.

**Comment by Veercodeprog** [comment]
what is the deadline of this project

**Comment by MSVaibhav4141** [comment]
According to my understanding, we can implement this by taking the user's type (admin or regular user) during the signup process and storing that userType in the same users array. Then, when the user logs in, we can check whether they are an admin or not. If the user is an admin, we can enable the privilege of adding questions using modules such as EJS. If the user is a regular user, we can skip that privilege.

Here's how the signup process should work
`````
<form action="/signup" method="post">
        <label for="email">Enter your email</label>
        <input type="email" name="email" id="">
        <label for="password">Enter the password</label>
        <input type="password" name="password" id="">
        <label for="user">User Type</label>
            <select name="userType">
                <option value="admin">admin</option>
                <option value="user">user</option>
            </select>
        
        <button type="submit">Signup</button>
    </form>
`````
we could store user info like this:-

`````
const newUser = {
        id : uid,
        upassword: password,
        utype: userType
    }
`````
Hope it helps

**Comment by Praashh** [comment]
@Mohit-sankhla02 bro it's pretty  we have to just create an array of token or we can simply generate keys for admins and if user have those key then he/she can simply add question.

**Comment by abishek-william** [comment]
> According to my understanding, we can implement this by taking the user's type (admin or regular user) during the signup process and storing that userType in the same users array. Then, when the user logs in, we can check whether they are an admin or not. If the user is an admin, we can enable the privilege of adding questions using modules such as EJS. If the user is a regular user, we can skip that privilege.
> 
> Here's how the signup process should work
> 
> ```
> <form action="/signup" method="post">
>         <label for="email">Enter your email</label>
>         <input type="email" name="email" id="">
>         <label for="password">Enter the password</label>
>         <input type="password" name="password" id="">
>         <label for="user">User Type</label>
>             <select name="userType">
>                 <option value="admin">admin</option>
>                 <option value="user">user</option>
>             </select>
>         
>         <button type="submit">Signup</button>
>     </form>
> ```
> 
> we could store user info like this:-
> 
> ```
> const newUser = {
>         id : uid,
>         upassword: password,
>         utype: userType
>     }
> ```
> 
> Hope it helps

Ok. But now everyone can create a account with admin privileges. is that right?

**Comment by Veercodeprog** [comment]
random web token i.e. called jwt refreshtokesn are used for security purpose and to check if user is logged in or not.More like a session,we use it.
the user is admin or not must be checked from the user-type key in users array.

**Comment by divyanshuagrawal999** [comment]
The way we can do it by using an roles list, this will further be helping in case when we have many different types of roles, we can simply update those access roles for a particular user then.
While authorizing for a particular task, we can simply call that middleware, to check whether or not the user is authorized for that task or not 
This can be done as follows:

# defining schema:
let user = {
    firstName: "",
    lastName: "",
    email: "",
    password: "",
    role: "user", //default (if admin specify admin)
  };

# Getting the token while logging in:
USERS.some((user) => {
    if (user.email == credentials.email) {
      if (user.password == credentials.password) {
        if (user.role === "user") res.json({ accessToken: "useraccessToken" });
        else {
          res.json({ accessToken: "adminaccessToken" });
        }
      } else {
        res.json("invalid credentials");
      }
    } else {
      res.json("user doesn't exist");
    }
  });


# authorizing user
const authHeader = req.headers.authorization || req.headers.Authorization;
  if (!authHeader.startsWith("Bearer ")) return res.sendStatus(401);
  console.log(authHeader);
  if (authHeader === "Bearer adminaccessToken") {
//PERFORM THE TASK
}
else{
"user is unauthorized"}

**Comment by Mohit-sankhla02** [comment]
> > According to my understanding, we can implement this by taking the user's type (admin or regular user) during the signup process and storing that userType in the same users array. Then, when the user logs in, we can check whether they are an admin or not. If the user is an admin, we can enable the privilege of adding questions using modules such as EJS. If the user is a regular user, we can skip that privilege.
> > Here's how the signup process should work
> > ```
> > <form action="/signup" method="post">
> >         <label for="email">Enter your email</label>
> >         <input type="email" name="email" id="">
> >         <label for="password">Enter the password</label>
> >         <input type="password" name="password" id="">
> >         <label for="user">User Type</label>
> >             <select name="userType">
> >                 <option value="admin">admin</option>
> >                 <option value="user">user</option>
> >             </select>
> >         
> >         <button type="submit">Signup</button>
> >     </form>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > we could store user info like this:-
> > ```
> > const newUser = {
> >         id : uid,
> >         upassword: password,
> >         utype: userType
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope it helps
> 
> Ok. But now everyone can create a account with admin privileges. is that right?

Yupp for that I can make it so that signing up with admin is on a different location something like /login/admin and post request there. And I will complicate the process like adding a shit ton of other details that you need to submit in order to be an admin.

**Comment by Mohit-sankhla02** [comment]
> The way I would recommend is using an roles list, this will further be helping in case when we have many different types of roles, we can simply update those access roles for a particular user then. While authorizing for a particular task, we can simply call that middleware, to check whether or not the user is authorized for that task or not This can be done as follows:
> 
> # defining schema:
> let user = { firstName: "", lastName: "", email: "", password: "", role: "user", //default (if admin specify admin) };
> 
> # Getting the token while logging in:
> USERS.some((user) => { if (user.email == credentials.email) { if (user.password == credentials.password) { if (user.role === "user") res.json({ accessToken: "useraccessToken" }); else { res.json({ accessToken: "adminaccessToken" }); } } else { res.json("invalid credentials"); } } else { res.json("user doesn't exist"); } });
> 
> # authorizing user
> const authHeader = req.headers.authorization || req.headers.Authorization; if (!authHeader.startsWith("Bearer ")) return res.sendStatus(401); console.log(authHeader); if (authHeader === "Bearer adminaccessToken") { //PERFORM THE TASK } else{ "user is unauthorized"}

This I understood 80%, rest I think it's like implementing JWT.
